export const Peças = [
  {
    id: 0,
    href: "https://pt.aliexpress.com/item/33038105890.html",
    target: "_blank",
    rel: "noreferrer",
    nome: "Placa mãe",
    preço: 497.75,
  },
  {
    id: 1,
    href: "https://pt.aliexpress.com/item/32881382889.html",
    target: "_blank",
    rel: "noreferrer",
    nome: "Processador",
    preço: 673.9,
  },
  {
    id: 2,
    href: "https://pt.aliexpress.com/item/32792886868.html",
    target: "_blank",
    rel: "noreferrer",
    nome: "Memória",
    preço: 452.96,
  },
  {
    id: 3,
    href: "https://pt.aliexpress.com/item/4000307321126.html",
    target: "_blank",
    rel: "noreferrer",
    nome: "Cooler",
    preço: 158.93,
  },
  {
    id: 4,
    href: "https://pt.aliexpress.com/item/1005001738246299.html",
    target: "_blank",
    rel: "noreferrer",
    nome: "Armazenamento",
    preço: 378.07,
  },
  {
    id: 5,
    href: "https://pt.aliexpress.com/item/4001297648724.html",
    target: "_blank",
    rel: "noreferrer",
    nome: "Dissipador",
    preço: 29.66,
  },
  {
    id: 6,
    href: "https://produto.mercadolivre.com.br/MLB-1684311870",
    target: "_blank",
    rel: "noreferrer",
    nome: "Gabinete",
    preço: 259.9,
  },
  {
    id: 7,
    href: "https://pt.aliexpress.com/item/33050578685.html",
    target: "_blank",
    rel: "noreferrer",
    nome: "Cooler Fan",
    preço: 150.0,
  },
  {
    id: 8,
    href: "https://www.pichau.com.br/fonte-corsair-cx-series-cx650-80-plus-bronze-650w-pfc-ativo-cp-9020122-ww",
    target: "_blank",
    rel: "noreferrer",
    classe: "caro",
    nome: "Fonte",
    preço: 449.0,
  },
  {
    id: 9,
    href: "",
    target: "",
    rel: "",
    classe: "caro",
    nome: "Placa de vídeo",
    preço: 940.0,
  },
];

export const Periféricos = [
  {
    id: 0,
    href: "https://www.pichau.com.br/teclado-mecanico-redragon-dark-avenger-lunar-white-rgb-switch-brown-k568w-rgb-pt-brown",
    target: "_blank",
    rel: "noreferrer",
    nome: "Teclado",
    preço: 299.89,
  },
  {
    id: 1,
    href: "https://www.amazon.com.br/Headphone-HV-H2232d-Ilumina%C3%A7%C3%A3o-Microfone-Conector/dp/B07N78G8GB/",
    target: "_blank",
    rel: "noreferrer",
    nome: "Headset",
    preço: 129.9,
  },
];
